apiversion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
   app: nginx
spec:
  replicas: 1
  selctor:
    matchLables:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      conatiners: 
        name: nginx
        image: nginx:1.16
        ports:
          conatinerPort: 8080
